import Link from 'next/link';
export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

const AboutPage = ()=>{
    return (
        <div>
            About Page
            <ul>
                 <li>
                            <Link href="/">Home</Link>
                          </li>
            </ul>
        </div>
    )
}
export default AboutPage;